CREATE TABLE `instant_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128) NOT NULL,
	`email` varchar(320),
	`phone` varchar(32),
	`address` text NOT NULL,
	`city` varchar(128),
	`state` varchar(64),
	`zip` varchar(16),
	`lat` decimal(10,7),
	`lng` decimal(10,7),
	`squareFootage` int,
	`stories` int,
	`exteriorMaterial` varchar(64),
	`propertyType` varchar(64),
	`services` json DEFAULT ('[]'),
	`subtotal` decimal(10,2) DEFAULT '0.00',
	`discountPercent` decimal(5,2) DEFAULT '0.00',
	`discountAmount` decimal(10,2) DEFAULT '0.00',
	`total` decimal(10,2) DEFAULT '0.00',
	`status` enum('pending','booked','declined','converted') NOT NULL DEFAULT 'pending',
	`emailConsent` boolean DEFAULT false,
	`smsConsent` boolean DEFAULT false,
	`convertedToLeadId` int,
	`convertedToQuoteId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instant_quotes_id` PRIMARY KEY(`id`)
);
