ALTER TABLE quote_tool_settings
  ADD COLUMN maxSqftAuto DECIMAL(10,2) NOT NULL DEFAULT 5000,
  ADD COLUMN maxLinearFtAuto DECIMAL(10,2) NOT NULL DEFAULT 800,
  ADD COLUMN maxStoriesAuto INT NOT NULL DEFAULT 3,
  ADD COLUMN maxWindowsAuto INT NOT NULL DEFAULT 120;
