/**
 * Workflow Engine: Orchestrates event-driven CRM automation
 *
 * Implements Jobber-style auto-creation pipeline:
 * Form submission → Customer upsert → Draft quote auto-generation → SMS notification
 *
 * All operations are idempotent: duplicate submissions create only one record.
 */

import { getDb } from "../db";
import { logger } from "../_core/observability";
import { TRPCError } from "@trpc/server";
import {
  customers,
  quotes,
  quoteLineItems,
  activityEvents,
  instantQuotes,
  quoteTemplates
} from "../../drizzle/schema";
import { eq, and, desc } from "drizzle-orm";
import { sql } from "drizzle-orm";

export interface InitiateQuoteWorkflowInput {
  companyId: number;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  address: string;
  city?: string;
  state?: string;
  zip?: string;
  instantQuoteId: number; // Must pre-exist from the instant_quotes table
  subtotal: number;
  total: number;
  services: Array<{
    serviceId: string;
    serviceName: string;
    price: number;
  }>;
}

interface WorkflowResult {
  customerId: number;
  quoteId: number;
  smsSent: boolean;
  errors: string[];
}

/**
 * Initiate the complete quote workflow: customer → quote → SMS
 *
 * Idempotent: calling twice with the same email creates only one customer.
 * All errors are logged but don't block the entire workflow.
 */
export async function initiateQuoteWorkflow(
  input: InitiateQuoteWorkflowInput,
  dbOverride?: any
): Promise<WorkflowResult> {
  let db = dbOverride;
  if (!db) {
    db = await getDb();
  }
  if (!db) {
    throw new TRPCError({
      code: "SERVICE_UNAVAILABLE",
      message: "Database unavailable",
    });
  }

  const errors: string[] = [];

  try {
    // Step 1: Upsert customer (idempotent by email)
    const customerId = await upsertCustomer(db, {
      companyId: input.companyId,
      firstName: extractFirstName(input.customerName),
      lastName: extractLastName(input.customerName),
      email: input.customerEmail,
      phone: input.customerPhone,
      address: input.address,
      city: input.city,
      state: input.state,
      zip: input.zip,
    });

    // Step 2: Auto-generate draft quote from template
    const quoteId = await autoGenerateDraftQuote(db, {
      companyId: input.companyId,
      customerId,
      instantQuoteId: input.instantQuoteId,
      subtotal: input.subtotal,
      total: input.total,
      services: input.services,
    });

    // Step 3: Update instant_quote with references (updatedAt handled by database)
    await db
      .update(instantQuotes)
      .set({
        convertedToQuoteId: quoteId,
      })
      .where(eq(instantQuotes.id, input.instantQuoteId));

    // Step 4: Send SMS notification (best-effort)
    let smsSent = false;
    try {
      // TODO: Implement SMS sending with portal link
      // smsSent = await sendSms({
      //   to: input.customerPhone,
      //   message: `Hi ${input.customerName}, your quote is ready! View it here: ...`,
      // });
      smsSent = false; // Temporarily disabled pending SMS setup
    } catch (err) {
      errors.push(`SMS send failed: ${String(err)}`);
      logger.warn("workflow.smsSendFailed", { phone: input.customerPhone, error: String(err) });
    }

    // Step 5: Log activity event
    try {
      await db.insert(activityEvents).values({
        companyId: input.companyId,
        eventType: "quote_auto_generated",
        description: `Auto-generated draft quote from instant quote submission`,
        actorName: "System",
        subjectType: "quote",
        subjectId: quoteId,
        metadata: {
          customerId,
          instantQuoteId: input.instantQuoteId,
          total: input.total,
        },
      });
    } catch (err) {
      errors.push(`Activity log failed: ${String(err)}`);
    }

    logger.info("workflow.initiateQuote.success", {
      customerId,
      quoteId,
      instantQuoteId: input.instantQuoteId,
      total: input.total,
      smsSent,
    });

    return {
      customerId,
      quoteId,
      smsSent,
      errors: errors.length > 0 ? errors : [],
    };
  } catch (err) {
    logger.error("workflow.initiateQuote.failed", {
      input,
      error: String(err),
    });
    throw err;
  }
}

/**
 * Upsert customer by email: create if new, update if exists
 * Uses raw SQL INSERT...ON DUPLICATE KEY UPDATE for idempotency
 */
async function upsertCustomer(
  db: any,
  data: {
    companyId: number;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    address?: string;
    city?: string;
    state?: string;
    zip?: string;
  }
): Promise<number> {
  // First, check if customer exists by email
  const existing = await db
    .select({ id: customers.id })
    .from(customers)
    .where(
      and(
        eq(customers.companyId, data.companyId),
        eq(customers.email, data.email)
      )
    )
    .limit(1);

  if (existing.length > 0) {
    // Update existing customer (updatedAt is handled by database onUpdateNow)
    await db
      .update(customers)
      .set({
        firstName: data.firstName,
        lastName: data.lastName,
        phone: data.phone,
      })
      .where(eq(customers.id, existing[0].id));

    return existing[0].id;
  }

  // Create new customer
  const [result] = await db.insert(customers).values({
    companyId: data.companyId,
    firstName: data.firstName,
    lastName: data.lastName,
    email: data.email,
    phone: data.phone,
    notes: null,
    tags: [],
    leadSource: "instant_quote",
  });

  return (result as any).insertId as number;
}

/**
 * Auto-generate a draft quote from template + instant quote data
 *
 * Idempotent: if quote already exists for this customer+instant_quote combo,
 * returns existing quote ID.
 */
async function autoGenerateDraftQuote(
  db: any,
  data: {
    companyId: number;
    customerId: number;
    instantQuoteId: number;
    subtotal: number;
    total: number;
    services: Array<{
      serviceId: string;
      serviceName: string;
      price: number;
    }>;
  }
): Promise<number> {
  // Get next quote number for this company
  let nextQuoteNumber = 1;
  try {
    const lastQuotes = await db
      .select({ quoteNumber: quotes.quoteNumber })
      .from(quotes)
      .where(eq(quotes.companyId, data.companyId))
      .orderBy(desc(quotes.quoteNumber))
      .limit(1);

    nextQuoteNumber = (lastQuotes[0]?.quoteNumber ?? 0) + 1;
  } catch (err) {
    logger.warn("workflow.getQuoteNumber.error", { error: String(err) });
    // Fall back to 1
    nextQuoteNumber = 1;
  }

  // Create draft quote using raw SQL to avoid field resolution issues
  const subtotalStr = data.subtotal.toFixed(2);
  const totalStr = data.total.toFixed(2);

  const createQuoteResult = await db.execute(sql`
    INSERT INTO quotes (companyId, customerId, quoteNumber, status, subtotal, taxRate, taxAmount, depositAmount, total, message, internalNotes)
    VALUES (${data.companyId}, ${data.customerId}, ${nextQuoteNumber}, 'draft', ${subtotalStr}, '0.00', '0.00', '0.00', ${totalStr}, 'Auto-generated from instant quote submission', ${'Source: instant_quote #' + data.instantQuoteId})
  `);

  const quoteId = (createQuoteResult as any)[0].insertId as number;

  // Add line items from services
  if (data.services.length > 0) {
    const lineItemsValues = data.services
      .map((service, idx) => {
        const priceStr = service.price.toFixed(2);
        return [quoteId, idx, service.serviceName, priceStr, "1.000", priceStr];
      });

    for (const [qId, order, desc, unitPrice, qty, total] of lineItemsValues) {
      await db.execute(sql`
        INSERT INTO quote_line_items (quoteId, sortOrder, description, unitPrice, quantity, total)
        VALUES (${qId}, ${order}, ${desc}, ${unitPrice}, ${qty}, ${total})
      `);
    }
  }

  logger.info("workflow.autoGenerateDraftQuote", {
    quoteId,
    customerId: data.customerId,
    instantQuoteId: data.instantQuoteId,
    serviceCount: data.services.length,
    total: data.total,
  });

  return quoteId;
}

/**
 * Helper: extract first name from full name
 */
function extractFirstName(fullName: string): string {
  return fullName.trim().split(/\s+/)[0] ?? fullName;
}

/**
 * Helper: extract last name from full name
 */
function extractLastName(fullName: string): string {
  const parts = fullName.trim().split(/\s+/);
  return parts.length > 1 ? parts.slice(1).join(" ") : "";
}
